export const Strings = {
  mealCart: "Meal Cart",
  description:
    "Your smart meal planning assistant. Save recipes, plan weeks, and shop instantly.",
  createAccount: "Create Account",
  logIn: "Log In",
  continueWithGoogle: "Continue with Google",
  continueWithApple: "Continue with Apple",
  signUp: "Sign Up",
  signup: "Sign up",
  signIn: "Sign In",
  alreadyHaveAccount: "Already have an account?",
  newUser: "New to the app",
  createYourAccount: "Create Your Account",
  startJourney: "Start your journey to organized meals ",
  welcomeBack: "Welcome Back",
  forgotPassword: "Forgot Password?",
  back: "Back",
  next: "Next",
  getStarted: "Get Started",
  resetPassword: "Reset Password",
  sendCode: "Send Code",
  rememberPassword: "Remember password?",
  saveAndLogin: "Save & Login",
  setNewPassword: "Set New Password",
  checkEmail: "Check Your Email",
  verify: "Verify",
  email: "Email",
  password: "Password",
  confirmPassword: "Confirm Password",
  name: "Name",
  mealsAreSecure:
    "Your meal plans and recipes will be securely synced to your account.",
  userNotRegistered: "User is not registered in the database",
  signinSuccessful: "Signin successful",
  signupSuccessfully: "Account created successfully!",
  signinFailed: "Signin failed",
  registrationFailed: "Registration failed",
  loginFailed: "Login failed",
  mealAdded: "Meal added successfully",
  mealUpdated: "Meal updated successfully",

  error_creating_meal: "Error creating meal",
  error_updating_meal: "Error updating meal",
  meal_deleted: "Meal deleted successfully",
  error_deleting_meal: "Error deleting meal",
  error_occurred_deleting_meal: "An error occurred while deleting the meal"
};
