export const Strings = {
mealCart: "Meal cart",
description: "Your smart meal planning assistant. Save recipes, plan weeks, and shop instantly.",
createAccount: "Create Account",
logIn: "Log In",
continueWithGoogle: "Continue with Google",
continueWithApple: "Continue with Apple",
signUp: "Sign Up",
signup: "Sign up",
signIn: "Sign In",
alreadyHaveAccount: "Already have an account?",
newUser: "New to the app",
createYourAccount: "Create your account",
welcomeBack: "Welcome Back",
forgotPassword: "Forgot Password?",
back: "Back",
next: "Next",
getStarted: "Get Started",
resetPassword: "Reset Password",
sendCode: "Send Code",
rememberPassword: "Remember password?",
saveAndLogin: "Save & Login",
setNewPassword: "Set New Password",
checkEmail: "Check your email",
verify: "Verify",
email: "Email",
password: "Password",
confirmPassword: "Confirm Password",
name: "Name",
};
