export const Strings = {
  mealDetail_info: "• 4 Servings • Medium",
  mealDetail_edit: "Edit",
  mealDetail_delete: "Delete",
  _5_mins: "5 Mins",
  _10_mins: "10 Mins",
  _15_mins: "15 Mins",
  mealDetail_ingredients: "Ingredients",
  mealDetail_instructions: "Instructions",
  mealDetail_description:
    "A rich and meaty sauce served over a bed of perfectly cooked spaghetti. A timeless family favorite that everyone will love.",
  mealDetail_ingredient_spaghetti: "Spaghetti",
  mealDetail_ingredient_spaghetti_qty: "400 g",
  mealDetail_ingredient_beef: "Ground Beef",
  mealDetail_ingredient_beef_qty: "500 g",
  mealDetail_ingredient_onion: "Onion",
  mealDetail_ingredient_onion_qty: "1 large",
  mealDetail_ingredient_garlic: "Garlic Cloves",
  mealDetail_ingredient_garlic_qty: "2",
  mealDetail_ingredient_tomatoes: "Chopped Tomatoes",
  mealDetail_ingredient_tomatoes_qty: "800 g",
  mealDetail_ingredient_paste: "Tomato Paste",
  mealDetail_ingredient_paste_qty: "2 tbsp",
  mealDetail_instruction_1:
    "Heat olive oil in a large pan. Sauté diced onion and garlic.",
  mealDetail_instruction_2: "Add ground beef and cook until browned.",
  mealDetail_instruction_3:
    "Stir in chopped tomatoes and tomato paste. Simmer for 20 minutes.",
  mealDetail_deleteMeal: "Delete Meal",
  mealDetail_deleteDesc:
    "This action is permanent and cannot be undone. You will lose access to this meal.",
  mealDetail_cancel: "Cancel",
  mealDetail_confirmDelete: "Delete",
  defaultServings_title: "Default Servings",
  defaultServings_subtitle:
    "You can set your meals servings for all your new meals.",
  defaultServings_label: "Servings",
  defaultServings_cancel: "Cancel",
  defaultServings_save: "Save",
  createMeal_editMeal: "Edit Meal",
  createMeal_createMeal: "Create Meal",
  createMeal_basicInfo: "Basic Information",
  createMeal_mealName: "Meal Name",
  createMeal_mealName_placeholder: "e.g. Classic Spaghetti",
  createMeal_mealDescription: "Meal Description",
  createMeal_mealDescription_placeholder: "A short summary of the meal...",
  createMeal_mealDescription_edit_placeholder:
    "A rich and meaty sauce served over a bed of perfectly cooked spaghetti. A timeless family favorite that everyone will love.",
  createMeal_imageUrl: "Image URL",
  createMeal_imageUrl_placeholder: "https://...",
  createMeal_imageUrl_edit_placeholder:
    "https://myfood.com/image/Classic Spaghetti Bolognese",
  createMeal_upload: "Upload",
  createMeal_remove: "Remove",
  createMeal_prepTime: "Prep Time (min)",
  createMeal_servings: "Servings",
  createMeal_difficulty: "Difficulty",
  createMeal_category: "Category",
  createMeal_ingredients: "Ingredients",
  createMeal_ingredientName: "Ingredient Name",
  createMeal_ingredientName_placeholder: "e.g. Tomato",
  createMeal_count: "Count",
  createMeal_unit: "Unit (weight)",
  createMeal_addIngredient: "Add Ingredient",
  createMeal_instruction: "Instruction",
  createMeal_addStep: "Add Step",
  createMeal_cancel: "Cancel",
  createMeal_discard: "Discard",
  createMeal_updateMeal: "Update Meal",
  createMeal_confirm: "Confirm",
  confirmationModal_title: "Are you sure?",
  confirmationModal_description: "This action cannot be undone.",
  confirmationModal_cancel: "Cancel",
  confirmationModal_confirm: "Confirm",
  verifyOtp_success: "OTP verified successfully!",
  verifyOtp_verificationFailed: "Verification Failed",
  verifyOtp_error: "Error",
  verifyOtp_unexpectedError: "An unexpected error occurred",
  verifyOtp_description: "We sent a 6-digit code to {email}",
  resetPassword_description:
    "Enter your email and we'll send you a code to get back into your account.",
  resetPassword_checkEmailTitle: "Check Your Email",
  resetPassword_checkEmailMessage:
    "A password reset link has been sent to your email address.",
  resetPassword_ok: "OK",
  resetPassword_error: "Error",
  resetPassword_unexpectedError: "An unexpected error occurred",

  mealPlanSettings_title: "Meal Plan Settings",
  mealPlanSettings_customize:
    "Customize the number and names of meals for your daily plans.",
  mealPlanSettings_addEveningSnacks: "Add Evening Snacks",
  mealPlanSettings_addMoreType: "Add More Type",
  mealPlanSettings_limitReached: "Limit Reached (Max 9 Slots)",
  mealPlanSettings_save: "Save Settings",
  mealPlanSettings_mealNameEmpty: "Meal name cannot be empty",
  mealPlanSettings_noNewPlans: "No new meal plans to save",
  createMealPlan_backToPlans: "Back to Plans",
  createMealPlan_yourMealPlan: "Your Meal Plan",
  createMealPlan_mySpecialMealPlan: "My special Meal Plan",
  divider_or: "OR",
  createMealPlan_startingDate: "Starting Date",
  createMealPlan_discard: "Discard",
  createMealPlan_save: "Save ",
  allergies_title: "Allergies & Intolerances",
  allergies_placeholder: "Press Enter to add a tag",
  allergies_save: "Save Allergies",
  lists_shoppingLists: "Shopping Lists",
  lists_created: "Created:",
  lists_markDone: "Mark Done",
  lists_viewList: "View List",
  plans_mealPlans: "Meal Plans",
  plans_started: "Started :",
  plans_created: "Created:",
  plans_viewPlan: "View Plan",
  plans_startPlan: "Start Plan",
  plans_noActivePlan: "No Active Plan",
  plans_testPlan: "Test Plan",
  plans_dayOf: "Day 3 of 7",
  plans_todaysMeal: "Today's Meal:",
  plans_breakfast: "Breakfast",
  plans_lunch: "Lunch",
  plans_dinner: "Dinner",
  plans_notPlanned: "Not planned",
  plans_avocadoToast: "Avocado Toast with...",
  plans_getShoppingList: "Get Shopping List",
  plans_pausePlan: "Pause Plan",
  plans_resumePlan: "Resume Plan",
  plans_yourOtherPlans: "Your Other Plans",
  plans_pauseMealPlan: "Pause Meal Plan?",
  plans_pauseDescription:
    "You can always resume the meal plan whenever you like to.",
  plans_cancel: "Cancel",
  plans_pause: "Pause",
  meals_myMeals: "My Meals",
  meals_browseMeals: "Browse Meals",
  meals_searchPlaceholder: "Search your meals...",
  updateProfileModal_title: "Update Profile",
  updateProfileModal_subtitle:
    "You can set your meals servings for all your new meals.",
  updateProfileModal_update: "Update",
  updateProfileModal_remove: "Remove",
  updateProfileModal_updateName: "Update Name",
  updateProfileModal_namePlaceholder: "Your Name",
  updateProfileModal_updateEmail: "Update Email",
  updateProfileModal_emailPlaceholder: "youemail@example.com",
  updateProfileModal_social: "Social",
  updateProfileModal_connectedWithGoogle: "Connected with Google",
  updateProfileModal_cancel: "Cancel",
  sendShoppingList_title: "Send To Shopping List",
  sendShoppingList_subtitle:
    "You can choose from existing list to add this item’s shopping requirements.",
  sendShoppingList_createNewList: "Create New List",
  sendShoppingList_availableLists: "Available Lists",
  sendShoppingList_created: "Created:",
  sendShoppingList_add: "Add",
  sendShoppingList_cancel: "Cancel",
  sendShoppingList_confirm: "Confirm",
  meals_recentMeals: "Recent Meals",
  meals_yourMeals: "Your Meals",
  meals_noMealsFound: "No meals found",
  meals_allMeals: "All Meals",
  mealCart: "Meal Cart",
  filterModal_filters: "Filters",
  filterModal_category: "Category",
  filterModal_difficulty: "Difficulty",
  filterModal_prepTime: "Prep Time",
  filterModal_reset: "Reset",
  filterModal_confirm: "Confirm",
  filterModal_breakfast: "Breakfast",
  filterModal_lunch: "Lunch",
  filterModal_dinner: "Dinner",
  filterModal_snacks: "Snacks",
  filterModal_easy: "Easy",
  filterModal_moderate: "Moderate",
  filterModal_challenging: "Challenging",
  filterModal_expert: "Expert",
  filterModal_prepTime_1: "< 5 Mins",
  filterModal_prepTime_2: "5 - 10 Mins",
  filterModal_prepTime_3: "10 - 15 Mins",
  filterModal_prepTime_4: "> 15 Mins",
  description:
    "Your smart meal planning assistant. Save recipes, plan weeks, and shop instantly.",
  createAccount: "Create Account",
  imagePickerModal_selectImage: "Select Image",
  imagePickerModal_takePhoto: "Take Photo",
  imagePickerModal_chooseFromGallery: "Choose from Gallery",
  imagePickerModal_cancel: "Cancel",
  imagePickerModal_cameraPermission: "Camera permission is required!",
  imagePickerModal_mediaLibraryPermission:
    "Media library permission is required!",
  logIn: "Log In",
  continueWithGoogle: "Continue with Google",
  continueWithApple: "Continue with Apple",
  signUp: "Sign Up",
  signup: "Sign up",
  signIn: "Sign In",
  alreadyHaveAccount: "Already have an account?",
  newUser: "New to the app",
  createYourAccount: "Create Your Account",
  startJourney: "Start your journey to organized meals ",
  welcomeBack: "Welcome Back",
  forgotPassword: "Forgot Password?",
  back: "Back",
  next: "Next",
  getStarted: "Get Started",
  resetPassword: "Reset Password",
  sendCode: "Send Code",
  rememberPassword: "Remember password?",
  saveAndLogin: "Save & Login",
  setNewPassword: "Set New Password",
  checkEmail: "Check Your Email",
  verify: "Verify",
  email: "Email",
  password: "Password",
  confirmPassword: "Confirm Password",
  name: "Name",
  mealsAreSecure:
    "Your meal plans and recipes will be securely synced to your account.",
  userNotRegistered: "User is not registered in the database",
  signinSuccessful: "Signin successful",
  signupSuccessfully: "Account created successfully!",
  signinFailed: "Signin failed",
  registrationFailed: "Registration failed",
  loginFailed: "Login failed",
  mealAdded: "Meal added successfully",
  signinDescription: "Log in to continue your meal planning.",
  home_mealCart: "MealCart",
  home_greeting: "Hello there!",
  home_subgreeting: "What delicious meal are you planning today?",
  home_nextMeal: "Your Next Meal",
  home_viewAll: "View All",
  home_noUpcomingMeals: "No upcoming meals. Add one!",
  home_mealCardDescription:
    "Some sort of description etc. Big Card if we want more information here",
  home_view: "View",
  home_addNewMeal: "Add New Meal",
  home_myMeals: "My Meals",
  home_recentMeals: "Recent Meals",
  home_viewAllRecent: "View All",
  home_moderate: "Moderate",
  home_lunch: "Lunch",
  home_dinner: "Dinner",
  dietaryPreferences_title: "Dietary Preferences",
  dietaryPreferences_save: "Save Preferences",
  dietaryPreferences_vegetarian: "Vegetarian",
  dietaryPreferences_vegan: "Vegan",
  dietaryPreferences_glutenFree: "Gluten-Free",
  dietaryPreferences_keto: "Keto",
  dietaryPreferences_paleo: "Paleo",
  dietaryPreferences_pescatarian: "Pescatarian",
  dietaryPreferences_dairyFree: "Dairy-Free",
  passwordReset_title: "Password Reset",
  passwordReset_currentPassword: "Current Password",
  passwordReset_newPassword: "New Password",
  passwordReset_confirmNewPassword: "Confirm New Password",
  passwordReset_updatePassword: "Update Password",
  profile_title: "Profile",
  profile_name: "Alex Doe",
  profile_email: "alex.doe@email.com",
  profile_mealCookingPreferences: "MEAL & COOKING PREFERENCES",
  profile_dietaryPreferences: "Dietary Preferences",
  profile_vegetarian: "Vegetarian",
  profile_allergies: "Allergies & Intolerances",
  profile_peanuts: "Peanuts",
  profile_mealPlanSettings: "Meal Plan Settings",
  profile_defaultServings: "Default Servings",
  profile_defaultServingsSubtitle: "2 People",
  profile_accountSecurity: "ACCOUNT & SECURITY",
  profile_changePassword: "Change Password",
  profile_deleteAccount: "Delete Account",
  profile_logout: "Logout",
  profile_appSettings: "APP SETTINGS",
  profile_helpSupport: "Help & Support",
  profile_aboutLegal: "About & Legal",
  profile_deleteAccountTitle: "Delete Account?",
  profile_deleteAccountDescription:
    "This action is permanent and cannot be undone. All your meals, plans, and lists will be lost.",
  profile_cancel: "Cancel",
  profile_confirmDelete: "Delete",
  testMealPlan_backToPlans: "Back to Plans",
  testMealPlan_title: "Test Plan",
  testMealPlan_startedOn: "Started on 27/09/2025",
  testMealPlan_removeTitle: "Remove Meal Plan?",
  testMealPlan_removeDescription:
    "Meal Plan will be removed and can no longer be accessible.",
  testMealPlan_cancel: "Cancel",
  testMealPlan_remove: "Remove",
  days: {
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",
  },
  testMealPlan_breakfast: "Breakfast",
  testMealPlan_lunch: "Lunch",
  testMealPlan_mySpecialMorningToast: "My special Morning Toast",
  testMealPlan_mySpecialBurger: "My Special Burger",
  testMealPlan_10min: "10 min",
  testMealPlan_15min: "15 min",
  testMealPlan_easy: "Easy",
  testMealPlan_medium: "Medium",
  testMealPlan_hard: "Hard",
  testPlanShopping_backToLists: "Back to Lists",
  testPlanShopping_title: "Test Plan ShoppingList",
  testPlanShopping_1meal: "1 meal",
  testPlanShopping_progress: "Progress",
  testPlanShopping_progressText: "2/4",
  testPlanShopping_bakery: "Bakery",
  testPlanShopping_wholeGrainBread: "Whole-grain bread",
  testPlanShopping_wholeGrainBreadAmount: "1 slice (Avocado Toast with Egg)",
  testPlanShopping_dairy: "Dairy",
  testPlanShopping_egg: "Egg",
  testPlanShopping_eggAmount: "1 (Avocado Toast with Egg)",
  testPlanShopping_pantry: "Pantry",
  testPlanShopping_redPepperFlakes: "Red pepper flakes",
  testPlanShopping_redPepperFlakesAmount: "1 pinch (Avocado Toast with Egg)",
  testPlanShopping_produce: "Produce",
  testPlanShopping_avocado: "Avocado",
  testPlanShopping_avocadoAmount: "0.5 (Avocado Toast with Egg)",
  introScreen_title: "Welcome to MealCart",
  introScreen_description: "All your meal planning, simplified in one place.",
  newPassword_description:
    "Your new password must be different from previous ones.",
  newPassword_success: "Password updated successfully!",
  newPassword_updateFailed: "Update Failed",
  newPassword_error: "Error",
  newPassword_unexpectedError: "An unexpected error occurred",
  welcomeMealCart_slide1_heading: "Welcome to MealCart  ",
  welcomeMealCart_slide1_subheading:
    "All your meal planning, simplified in one place.",
  welcomeMealCart_slide2_heading: "Build Your Perfect week",
  welcomeMealCart_slide2_subheading:
    "Create custom meal plans from your favorite receipes with just a few taps",
  welcomeMealCart_slide3_heading: "Shop Smarter,  Not Harder",
  welcomeMealCart_slide3_subheading:
    "Automatically generate an organized shopping list from your plan. Never forget an ingredient again.",
  welcomeMealCart_back: "Back",
  welcomeMealCart_getStarted: "Get Started",
  welcomeMealCart_next: "Next",
  addItemToList_title: "Select Meals to Shop For",
  addItemToList_subtitle:
    "Choose one or more meals to generate a combined list.",
  addItemToList_searchPlaceholder: "Search your meals...",
  addItemToList_addManualLabel: "Add item Manually",
  addItemToList_searchIngredient: "Search Ingredient",
  addItemToList_add: "Add",
  addItemToList_cancel: "Cancel",
  addItemToList_generateList: "Generate List",
  createList_createNewList: "Create New List",
  createPlan_selectAMeal: "Select a Meal",
  createList_listDetails: "List Details",
  createList_listName: "List Name",
  createList_listName_placeholder: "Classic Spaghetti",
  createList_shoppingDay: "Shopping Day",
  createList_shoppingDay_placeholder: "date",
  createList_items: "Items",
  createList_importedFrom: "imported from [Meal Name]",
  createList_addExtraItems: "Add extra items",
  createList_discard: "Discard",
  createList_saveShoppingList: "Save Shopping List",
  createList_category: "Category",
  mealUpdated: "Meal updated successfully",

  error_creating_meal: "Error creating meal",
  error_updating_meal: "Error updating meal",
  meal_deleted: "Meal deleted successfully",
  error_deleting_meal: "Error deleting meal",
  error_occurred_deleting_meal: "An error occurred while deleting the meal",
  units: {
    _100_grams: "100 grm",
    _200_grams: "200 grm",
    _1_kg: "1 kg",
    _50_ml: "50 ml",
    _100_ml: "100 ml",
    _250_ml: "250 ml",
    _500_ml: "500 ml",
    _1_litre: "1 Litre",
    tablespoon: "tablespoon",
    teaspoon: "teaspoon",
    cup: "cup",
  },
  fruit: "fruit",
  vegetable: "vegetable",
  meat: "meat",
  liquid: "liquid",
  veggies: "veggie",
  error_fetching_dietary_preferences: "Failed to fetch dietary preferences",
  error_adding_meal_plan: "Failed to add meal plan",
  error_deleting_meal_plan: "Failed to delete meal plan",
  error_updating_meal_plan: "Failed to update meal plan",
  error_fetching_meal_plans: "Failed to fetch meal plans",
  error_adding_plan: "Failed to add plan",
  error_fetching_plans: "Failed to fetch plans",
  error_updating_plan: "Failed to update plan",
  error_deleting_plan: "Failed to delete plan",
  plan_saved_successfully: "Plan saved successfully!",
  plan_updated_successfully: "Plan updated successfully!",

  meals: "meals",
  unknown_plan: "Unknown Plan",
};
